const { app, dialog } = require('electron');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
// Never alter a developer's actual playback settings during a smoke test.
const userData = fs.mkdtempSync(path.join(os.tmpdir(), 'audiority-ui-'));
app.setPath('userData', userData);
app.on('will-quit', () => fs.rmSync(userData, { recursive: true, force: true }));
const timeout = setTimeout(() => { console.error('UI smoke test timed out'); app.exit(1); }, 60000);
app.on('browser-window-created', (_event, window) => {
  const errors = [];
  window.webContents.on('console-message', (_event, details) => { if (details.level === 'error') errors.push(details.message); });
  window.webContents.once('did-finish-load', async () => {
    try {
      const state = await window.webContents.executeJavaScript(`({ title: document.title, bridge: typeof window.audiority.start, queue: document.getElementById('count').textContent, startDisabled: document.getElementById('start').disabled, node: typeof require })`);
      assert.deepEqual(state, { title: 'Audiority', bridge: 'function', queue: '0', startDisabled: true, node: 'undefined' });
      await window.webContents.executeJavaScript('window.audiority.clear()');
      const execute = code => window.webContents.executeJavaScript(code);
      const waitFor = async code => {
        for (let i = 0; i < 100; i++) { if (await execute(code)) return; await new Promise(resolve => setTimeout(resolve, 50)); }
        throw new Error(`Timed out waiting for ${code}`);
      };
      await waitFor(`document.getElementById('catalog-count').textContent.includes('126')`);
      const progressChecks = await execute(`(() => {
        const item = { id: 'progress-test', name: 'ETA test', status: 'Converting', progress: 0.5, progressStart: Date.now() - 10000 };
        items.set(item.id, item);
        const card = element('article'); card.dataset.id = item.id; card.append(element('span', 'status')); $('queue').append(card);
        patchProgress({ id: item.id, status: 'Converting', progress: 0.5 });
        const eta = /^50% · ~(10|11)s remaining$/.test(card.querySelector('.progress-text').textContent);
        const thickness = getComputedStyle(card.querySelector('progress')).height === '6px';
        item.status = 'Verifying'; patchProgress({ id: item.id, status: 'Verifying', progress: 0.99 });
        const verifying = card.querySelector('.progress-text').textContent === 'Verifying output...';
        item.status = 'Complete'; item.progress = 1;
        const complete = createProgress(item).querySelector('.progress-text').textContent === 'Complete';
        item.status = 'Converting'; item.progress = 0; patchProgress({ id: item.id, status: 'Converting', progress: 0 });
        const reset = !item.progressStart && card.querySelector('.progress-text').textContent === '0% · Estimating…';
        const originalPage = currentPage; currentPage = 'settings'; item.progress = 0.1; patchProgress({ id: item.id, status: 'Converting', progress: 0.1 });
        const offscreen = !!item.progressStart; currentPage = originalPage;
        items.delete(item.id); card.remove();
        return { eta, thickness, verifying, complete, reset, offscreen };
      })()`);
      assert.ok(Object.values(progressChecks).every(Boolean), JSON.stringify(progressChecks));
      const languageRoundTrip = await execute(`(() => {
        const original = readDraft();
        fillDraft({ ...original, allowedLanguages: ['eng', 'jpn'], keepDefaultTrack: false });
        const value = readDraft();
        const correct = value.allowedLanguages.join(',') === 'eng,jpn' && value.keepDefaultTrack === false;
        fillDraft(original);
        return correct && !!$('pref-allowedLanguages') && !!$('pref-keepDefaultTrack');
      })()`);
      assert.equal(languageRoundTrip, true);
      const reconciliationChecks = await execute(`(() => {
        const originalPage = currentPage; currentPage = 'queue';
        const make = i => ({ id: 'reconcile-' + i, name: 'Episode ' + i, status: 'Inspecting', tracks: [] });
        items.set('reconcile-0', make(0)); render();
        const first = $('queue').querySelector('article');
        const head = first.querySelector('.item-head');
        for (let i = 1; i < 55; i++) { items.set('reconcile-' + i, make(i)); render(); }
        const retained = first === $('queue').querySelector('article') && head === first.querySelector('.item-head');
        const pagination = $('queue').querySelector('.queue-pagination');
        render(); const stableNav = pagination === $('queue').querySelector('.queue-pagination');
        items.get('reconcile-54').priority = 100;
        items.get('reconcile-53').priority = 101; render();
        const priorityOrder = $('queue').children[0].dataset.id === 'reconcile-53' && $('queue').children[1].dataset.id === 'reconcile-54';
        delete items.get('reconcile-54').priority; delete items.get('reconcile-53').priority; render();
        const item = items.get('reconcile-0'); item.status = 'Ready';
        item.tracks = [{ sourceCodec: 'flac', codec: 'dca', action: 'encode', channels: 6, language: 'eng', reason: 'First plan' }]; render();
        const readyButton = !!first.querySelector('.prioritize-item');
        const details = first.querySelector('details'); details.open = true; expandedTracks.add(item.id);
        render(); const retainedDetails = details === first.querySelector('details') && details.open;
        item.tracks[0].reason = 'Changed profile'; render();
        const refreshed = first.textContent.includes('Changed profile') && first.querySelector('details').open;
        item.status = 'Complete'; item.output = '/test/output.mkv'; item.progress = 1; render();
        const complete = first.querySelector('.progress-text').textContent === 'Complete' && !!first.querySelector('.reveal-output') && !first.querySelector('.prioritize-item');
        item.status = 'Error'; item.error = 'Test failure'; item.warnings = ['Test warning']; render(); render();
        const messages = first.querySelectorAll('.item-messages .error').length === 1 && first.textContent.includes('Test warning');
        delete item.error; item.warnings = []; delete item.output; delete item.progress; item.status = 'Ready'; render();
        const cleared = !first.querySelector('.item-messages .error') && !first.querySelector('.reveal-output') && !first.querySelector('.progress-wrap');
        pagination.lastElementChild.click();
        const nextPage = $('queue').querySelectorAll('article').length === 5 && $('queue').querySelector('article').dataset.id === 'reconcile-50';
        for (let i = 0; i < 55; i++) items.delete('reconcile-' + i);
        expandedTracks.delete(item.id); render();
        const empty = !$('queue').querySelector('article') && !!$('queue').querySelector('.queue-empty');
        currentPage = originalPage;
        return { retained, stableNav, priorityOrder, readyButton, retainedDetails, refreshed, complete, messages, cleared, nextPage, empty };
      })()`);
      assert.ok(Object.values(reconciliationChecks).every(Boolean), JSON.stringify(reconciliationChecks));
      assert.equal(await execute(`!!document.getElementById('matrix-panel') && !document.getElementById('advanced-panel') && !document.getElementById('compatibility-panel')`), true);
      await execute(`document.getElementById('advanced-rules-open').click()`);
      assert.equal(await execute(`document.getElementById('advanced-rules-dialog').open && document.getElementById('rule-list').closest('dialog').id === 'advanced-rules-dialog' && document.getElementById('downmix-list').closest('dialog').id === 'advanced-rules-dialog'`), true);
      await window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Escape' });
      await window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Escape' });
      await waitFor(`!document.getElementById('advanced-rules-dialog').open`);
      await execute(`document.getElementById('advanced-rules-open').click(); document.getElementById('advanced-rules-done').click()`);
      assert.equal(await execute(`!document.getElementById('advanced-rules-dialog').open`), true);
      const matrixChecks = await execute(`(() => {
        const original = readDraft();
        $('profile-keep-original').checked = true;
        if (!readDraft().keepOriginal) throw new Error('Compatibility checkbox mapping failed');
        fillDraft(original);
        if ($('profile-keep-original').checked !== original.keepOriginal) throw new Error('Compatibility checkbox round-trip failed');
        $('profile-normalize').checked = true;
        const normalization = readDraft().normalizeVolume;
        fillDraft(original);
        if (!normalization || $('profile-normalize').checked !== original.normalizeVolume) throw new Error('Normalization form round-trip failed');
        const legacy = { ...original, advanced: true, extractDtsCore: false, allowDownmix: true,
          excludedFormats: ['eac3', 'mp3'], downmixRules: [{ source: '7.1', target: '3.1' }],
          rules: [{ source: 'flac', scope: 'surround', target: 'dts' }, { source: 'alac', scope: 'surround', target: 'ac3' },
            { source: 'aac', scope: 'stereo', target: 'pcm' }, { source: 'dtshd', scope: 'surround', target: 'ac3' }] };
        fillDraft(legacy);
        const roundTrip = JSON.stringify(readDraft()) === JSON.stringify(legacy);
        const divergent = ['lossless', 'other', 'dtshd'].every(id => document.getElementById('matrix-' + id).value === 'auto');
        const set = (id, value) => { const node = document.getElementById('matrix-' + id); node.value = value; node.dispatchEvent(new Event('change', { bubbles: true })); };
        set('eac3', 'ac3'); set('lossless', 'dts'); set('dtshd', 'core'); set('other', 'pcm');
        const result = readDraft();
        const repeated = JSON.stringify(result) === JSON.stringify(readDraft());
        fillDraft(result);
        const reload = JSON.stringify(readDraft()) === JSON.stringify(result);
        const specificPreserved = result.rules.some(r => r.source === 'aac' && r.scope === 'stereo' && r.target === 'pcm') && result.rules.some(r => r.source === 'dtshd' && r.scope === 'surround');
        const fallback = result.lossless === 'dts' && result.lossy === 'pcm' && result.stereo === 'pcm';
        const mappings = !result.excludedFormats.includes('eac3') && result.rules.some(r => r.source === 'eac3' && r.scope === 'any' && r.target === 'ac3') && result.extractDtsCore && result.allowed.includes('pcm');
        const downmix = JSON.stringify(result.downmixRules) === JSON.stringify(legacy.downmixRules);
        fillDraft(original);
        return { roundTrip, divergent, repeated, reload, specificPreserved, fallback, mappings, downmix };
      })()`);
      assert.ok(Object.values(matrixChecks).every(Boolean), JSON.stringify(matrixChecks));
      assert.equal(await execute(`document.getElementById('workspace').hidden`), true);
      assert.equal(await execute(`document.getElementById('matrix-panel').closest('#advanced-rules-dialog') !== null && !document.getElementById('advanced-rules-dialog').open`), true);
      await execute(`document.getElementById('advanced-rules-open').click()`);
      assert.equal(await execute(`document.getElementById('advanced-rules-dialog').open`), true);
      await execute(`document.getElementById('advanced-rules-done').click()`);
      await waitFor(`!document.getElementById('advanced-rules-dialog').open && document.activeElement.id === 'advanced-rules-open'`);
      await execute(`document.getElementById('avr-search').value='bose v20'; document.getElementById('avr-search').dispatchEvent(new Event('input'));`);
      assert.equal(await execute(`document.querySelectorAll('#avr-results button').length`), 1);
      await execute(`document.querySelector('#avr-results button').click(); document.getElementById('receiver-next').click();`);
      await execute(`document.getElementById('allow-downmix').checked=true; document.getElementById('extract-dts-core').checked=true; document.querySelector('#excluded-formats input[value="eac3"]').checked=true; document.querySelector('#downmix-list select[data-field="target"]').value='3.1';`);
      assert.equal(await execute(`document.getElementById('playback-page').hidden`), false);
      await execute(`document.getElementById('media-platform').value='jellyfin'; document.getElementById('playback-device').value='shield-tv-pro'; document.getElementById('passthrough').value='enabled'; document.getElementById('path-confirmed').checked=true; for(const el of document.querySelectorAll('#path-formats input')) el.checked=['dts','ac3','pcm'].includes(el.value); document.getElementById('path-confirmed').dispatchEvent(new Event('change',{bubbles:true}));`);
      await waitFor(`document.getElementById('profile-preview').textContent.includes('Bose Lifestyle V20') && !document.getElementById('setup-save').disabled`);
      await execute(`document.getElementById('profile-name').value='Living room'; document.getElementById('setup-save').click()`);
      await waitFor(`!document.getElementById('workspace').hidden`);
      const stored = JSON.parse(fs.readFileSync(path.join(userData, 'playback-profiles.json'), 'utf8'));
      assert.equal(stored.profiles[0].settings.receiverId, 'bose-lifestyle-v20'); assert.equal(stored.profiles[0].settings.platform, 'jellyfin');
      assert.equal(stored.profiles[0].settings.extractDtsCore, true); assert.equal(stored.profiles[0].settings.allowDownmix, true);
      assert.deepEqual(stored.profiles[0].settings.excludedFormats, ['eac3']);
      assert.deepEqual(stored.profiles[0].settings.downmixRules, [{ source: '7.1', target: '3.1' }]);
      await execute(`document.getElementById('duplicate-profile').click(); document.getElementById('dialog-name').value='Bedroom'; document.getElementById('profile-dialog-form').requestSubmit()`);
      await waitFor(`document.getElementById('profile-count').textContent === '2' && !document.getElementById('profile-dialog').open`);
      await execute(`document.getElementById('rename-profile').click(); document.getElementById('dialog-name').value='Bedroom TV'; document.getElementById('profile-dialog-form').requestSubmit()`);
      await waitFor(`document.querySelector('.profile-entry.active strong').textContent === 'Bedroom TV'`);
      await execute(`document.querySelector('#profile-list button').click()`);
      await waitFor(`document.querySelector('.profile-entry.active strong').textContent === 'Living room'`);
      await execute(`document.getElementById('new-profile').click()`);
      assert.equal(await execute(`document.getElementById('profile-name').value`), '');
      await execute(`document.getElementById('setup-cancel').click()`);
      await execute(`document.getElementById('delete-profile').click(); document.getElementById('profile-dialog-form').requestSubmit()`);
      await waitFor(`document.getElementById('profile-count').textContent === '1' && !document.getElementById('profile-dialog').open`);
      await execute(`document.getElementById('change-setup').click(); document.getElementById('custom-receiver').click(); document.getElementById('add-rule').click();`);
      assert.equal(await execute(`document.querySelectorAll('#rule-list .rule-row').length`), 1);
      assert.equal(await execute(`document.getElementById('advanced-enabled').checked`), true);
      await execute(`document.getElementById('setup-cancel').click()`);
      assert.equal(await execute(`document.getElementById('workspace').hidden`), false);
      await waitFor(`!document.getElementById('advanced-rules-dialog').open`);
      await waitFor(`document.getElementById('theme-select').options.length === 12`);
      await execute(`document.getElementById('nav-settings').click()`);
      await waitFor(`!document.getElementById('settings-page').hidden`);
      assert.equal(await execute(`!document.querySelector('header #appearance-open') && !document.getElementById('about-toggle') && document.getElementById('about-panel').closest('#settings-page') !== null && !document.getElementById('about-panel').hidden && document.getElementById('theme-form').closest('#app-settings-form') === null`), true);
      await execute(`document.getElementById('theme-select').value='graphite'; document.getElementById('theme-select').dispatchEvent(new Event('change'))`);
      await waitFor(`document.documentElement.dataset.theme === 'graphite' && !document.getElementById('theme-create').disabled`);
      await execute(`document.getElementById('theme-create').click(); document.getElementById('theme-name').value='Custom smoke theme'; document.querySelector('#theme-colors input[data-token="accent"]').value='#77bbcc'; document.getElementById('theme-form').dispatchEvent(new Event('input')); document.getElementById('theme-form').requestSubmit()`);
      await waitFor(`document.getElementById('theme-select').options.length === 13 && document.getElementById('theme-form').hidden`);
      assert.equal(await execute(`document.documentElement.style.getPropertyValue('--theme-accent')`),'#77bbcc');
      await execute(`document.getElementById('theme-edit').click(); document.getElementById('theme-name').value='Edited smoke theme'; document.getElementById('theme-form').requestSubmit()`);
      await waitFor(`document.getElementById('theme-select').selectedOptions[0].textContent === 'Edited smoke theme'`);
      await execute(`document.getElementById('nav-queue').click()`);
      const { run } = require('../src/engine'); const { toolPaths } = require('../src/tools');
      const show = path.join(userData,'Anime','Season 01'); fs.mkdirSync(show,{recursive:true});
      await run(toolPaths().ffmpeg,['-v','error','-f','lavfi','-i','anullsrc=r=48000:cl=stereo','-t','0.1','-c:a','flac',path.join(show,'Episode 01.mkv')]);
      fs.writeFileSync(path.join(show,'Episode 01.eng.srt'),'1\n00:00:00,000 --> 00:00:00,100\nTest\n');
      const originalDialog = dialog.showOpenDialog;
      dialog.showOpenDialog = async () => ({canceled:false,filePaths:[path.dirname(show)]});
      await execute(`document.getElementById('import-folder').click()`);
      await waitFor(`document.getElementById('count').textContent === '1' && document.getElementById('cancel-import').hidden`);
      assert.ok(await execute(`document.getElementById('queue').textContent.includes('Anime') && document.getElementById('queue').textContent.includes('1 external subtitle')`));
      await execute(`document.querySelector('#queue .prioritize-item').click()`);
      await waitFor(`items.values().next().value.priority > 0 && !document.querySelector('#queue .prioritize-item').disabled`);
      const priorityState = JSON.parse(fs.readFileSync(path.join(userData, 'queue.json'), 'utf8'));
      assert.ok(priorityState.items[0].priority > 0);
      assert.equal(await execute(`window.audiority.prioritizeItem('missing-id').then(() => false, () => true)`), true);
      await execute(`document.getElementById('import-folder').click()`);
      await waitFor(`document.getElementById('import-result').textContent.includes('1 already queued')`);
      dialog.showOpenDialog = originalDialog;
      await execute(`document.getElementById('nav-settings').click()`);
      await waitFor(`!document.getElementById('settings-page').hidden && document.querySelectorAll('#theme-presets button').length === 12`);
      await execute(`document.getElementById('pref-compact').checked=true; document.getElementById('pref-reducedMotion').checked=true; document.getElementById('pref-outputSuffix').value='.compatible'; document.getElementById('pref-inspectionConcurrency').value='3'; document.getElementById('app-settings-form').requestSubmit()`);
      await waitFor(`document.getElementById('settings-result').textContent === 'Settings saved.'`);
      fs.writeFileSync(path.join(os.tmpdir(), 'audiority-settings-preview.png'), (await window.webContents.capturePage()).toPNG());
      const prefs = JSON.parse(fs.readFileSync(path.join(userData, 'app-settings.json'), 'utf8'));
      assert.equal(prefs.compact, true); assert.equal(prefs.inspectionConcurrency, 3); assert.equal(prefs.storeFilenames, false);
      const outputFolder = path.join(userData, 'Converted'); fs.mkdirSync(outputFolder);
      dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [outputFolder] });
      await execute(`document.getElementById('settings-pick-output').click()`);
      await waitFor(`document.getElementById('settings-output').textContent === ${JSON.stringify(outputFolder)}`);
      assert.equal(await execute(`document.getElementById('destination').textContent === ${JSON.stringify(outputFolder)} && document.getElementById('folder').closest('footer') !== null`), true);
      await execute(`document.getElementById('nav-queue').click(); chooseOutputFolder()`);
      await waitFor(`document.getElementById('settings-output').textContent === ${JSON.stringify(outputFolder)} && !document.getElementById('folder').disabled`);
      dialog.showOpenDialog = originalDialog;
      // Hold the active conversion briefly so pause/resume IPC tests are deterministic,
      // even when the real FFmpeg fixture finishes in a fraction of a second.
      const { Engine } = require('../src/engine');
      // Never send fixture files to the real OS Trash during automated tests.
      const { shell } = require('electron');
      const originalTrashItem = shell.trashItem;
      const trashedSources = [];
      shell.trashItem = async file => { trashedSources.push(file); };
      await execute(`$('nav-settings').click()`);
      await waitFor(`!$('settings-page').hidden`);
      assert.equal(await execute(`$('pref-trashOriginals').checked`), false);
      const watchDialog = dialog.showOpenDialog;
      dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [userData] });
      await execute(`$('settings-pick-watch').click()`);
      await waitFor(`$('settings-watch-folder').textContent === ${JSON.stringify(userData)}`);
      dialog.showOpenDialog = watchDialog;
      await execute(`$('pref-watchEnabled').checked = true; $('app-settings-form').requestSubmit()`);
      await waitFor(`$('settings-result').textContent === 'Settings saved.' && !$('settings-save').disabled`);
      const watchPreferences = JSON.parse(fs.readFileSync(path.join(userData, 'app-settings.json'), 'utf8'));
      assert.equal(watchPreferences.watchEnabled, true);
      assert.equal(watchPreferences.watchFolder, userData);
      await execute(`$('nav-queue').click(); $('nav-settings').click()`);
      await waitFor(`!$('settings-page').hidden && $('pref-watchEnabled').checked`);
      await execute(`$('pref-watchEnabled').checked = false`);
      await execute(`$('pref-trashOriginals').checked = true; $('app-settings-form').requestSubmit()`);
      await waitFor(`$('settings-result').textContent === 'Settings saved.' && !$('settings-save').disabled`);
      assert.equal(JSON.parse(fs.readFileSync(path.join(userData, 'app-settings.json'), 'utf8')).trashOriginals, true);
      const originalConvert = Engine.prototype.convert;
      let releaseConversion;
      const conversionGate = new Promise(resolve => { releaseConversion = resolve; });
      Engine.prototype.convert = async function (...args) { await conversionGate; return originalConvert.apply(this, args); };
      await execute(`document.getElementById('nav-queue').click(); document.getElementById('start').click()`);
      await waitFor(`running && !$('pause').hidden`);
      await execute(`$('pause').click()`);
      await waitFor(`queuePaused && !pauseRequestPending && $('pause').textContent === 'Resume'`);
      assert.equal(await execute(`$('summary').textContent === 'Queue Paused. The active conversion will finish safely.'`), true);
      // Repeated pause requests must not replace the resolver and strand the runner.
      await execute(`window.audiority.pause()`);
      await execute(`$('pause').click()`);
      await waitFor(`!queuePaused && !pauseRequestPending && $('pause').textContent === 'Pause'`);
      await execute(`$('pause').click()`);
      await waitFor(`queuePaused && !pauseRequestPending`);
      releaseConversion();
      Engine.prototype.convert = originalConvert;
      await waitFor(`[...items.values()].some(item => item.status === 'Complete')`);
      // A paused final job must finish the run without requiring Resume or Cancel.
      await waitFor(`!running && !queuePaused && $('pause').hidden`);
      assert.equal(trashedSources.length, 1);
      assert.ok(fs.existsSync(trashedSources[0]));
      shell.trashItem = originalTrashItem;
      await execute(`window.audiority.pause()`);
      assert.equal(await execute(`queuePaused`), false);
      await execute(`window.audiority.start()`);
      await waitFor(`!running && !queuePaused`);
      await execute(`document.getElementById('nav-statistics').click()`);
      await waitFor(`!document.getElementById('statistics-page').hidden && document.getElementById('stats-recent').textContent.includes('completed')`);
      fs.writeFileSync(path.join(os.tmpdir(), 'audiority-statistics-preview.png'), (await window.webContents.capturePage()).toPNG());
      const stats = JSON.parse(fs.readFileSync(path.join(userData, 'statistics.json'), 'utf8'));
      assert.equal(stats.totals.completed, 1); assert.equal(stats.totals.encoded, 1);
      assert.ok(stats.totals.outputBytes > 0); assert.equal(stats.recent[0].filename, undefined);
      assert.ok(fs.existsSync(path.join(outputFolder, 'Anime', 'Season 01', 'Episode 01.compatible.mkv')));
      await execute(`document.getElementById('nav-queue').click()`);
      await execute(`location.reload()`);
      await waitFor(`document.readyState === 'complete' && !document.getElementById('workspace').hidden && document.getElementById('active-profile').textContent.includes('Bose Lifestyle V20')`);
      await waitFor(`document.getElementById('theme-select').selectedOptions[0]?.textContent === 'Edited smoke theme'`);
      assert.equal(await execute(`document.documentElement.classList.contains('compact') && document.documentElement.classList.contains('reduced-motion')`), true);
      assert.equal(await execute(`document.getElementById('destination').textContent`), outputFolder);
      await execute(`document.getElementById('change-setup').click()`);
      assert.equal(await execute(`document.getElementById('allow-downmix').checked && document.getElementById('extract-dts-core').checked && document.querySelector('#excluded-formats input[value="eac3"]').checked && document.querySelector('#downmix-list select[data-field="target"]').value === '3.1'`), true);
      await execute(`document.getElementById('setup-cancel').click()`);
      assert.equal(await execute(`document.documentElement.style.getPropertyValue('--theme-accent')`),'#77bbcc');
      assert.deepEqual(errors, []);
      const screenshot = await window.webContents.capturePage();
      fs.writeFileSync(path.join(os.tmpdir(), 'audiority-desktop-preview.png'), screenshot.toPNG());
      await execute(`document.getElementById('delete-profile').click(); document.getElementById('profile-dialog-form').requestSubmit()`);
      await waitFor(`document.getElementById('profile-count').textContent === '0' && !document.getElementById('setup').hidden && !document.getElementById('profile-dialog').open`);
      assert.equal(await execute(`document.getElementById('workspace').hidden`), true);
      console.log('UI smoke test passed: profiles, folder import, 12 themes, settings/navigation persistence, real conversion/statistics, and reload.');
      clearTimeout(timeout); app.exit(0);
    } catch (error) { console.error(error); clearTimeout(timeout); app.exit(1); }
  });
});
require('../src/main');